version: '3'

services:
    api-solid-pg:
        image: bitnami/postgresql
        ports:
            - '5436:5432'
        environment:
            - POSTGRESQL_USERNAME=isteen
            - POSTGRESQL_PASSWORD=isteen
            - POSTGRESQL_DATABASE=isteen_postgres_db